// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  topicId: __t.u64().name("topic_id"),
  mode: __t.string(),
  a: __t.identity(),
  b: __t.identity(),
  status: __t.string(),
  scoreA: __t.i32().name("score_a"),
  scoreB: __t.i32().name("score_b"),
  likes: __t.u32(),
  msgCount: __t.u32().name("msg_count"),
  summary: __t.string(),
  phase: __t.string(),
  phaseStartedAt: __t.timestamp().name("phase_started_at"),
  engagementStarter: __t.string().name("engagement_starter"),
  currentTurn: __t.string().name("current_turn"),
  remainingA: __t.u64().name("remaining_a"),
  remainingB: __t.u64().name("remaining_b"),
  openingA: __t.bool().name("opening_a"),
  openingB: __t.bool().name("opening_b"),
  closingA: __t.bool().name("closing_a"),
  closingB: __t.bool().name("closing_b"),
  yieldedSide: __t.string().name("yielded_side"),
  passesA: __t.u32().name("passes_a"),
  passesB: __t.u32().name("passes_b"),
  resultJson: __t.string().name("result_json"),
  createdAt: __t.timestamp().name("created_at"),
  lastAt: __t.timestamp().name("last_at"),
});
