// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  chatId: __t.u64().name("chat_id"),
  sender: __t.identity(),
  side: __t.string(),
  text: __t.string(),
  pts: __t.option(__t.i32()),
  why: __t.option(__t.string()),
  sentAt: __t.timestamp().name("sent_at"),
});
