// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  topicId: __t.u64().name("topic_id"),
  shown: __t.u32(),
  lastShownAt: __t.timestamp().name("last_shown_at"),
  lastOpenAt: __t.timestamp().name("last_open_at"),
  engaged: __t.bool(),
  hiddenUntil: __t.timestamp().name("hidden_until"),
});
