// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  title: __t.string(),
  category: __t.string(),
  sideA: __t.string().name("side_a"),
  sideB: __t.string().name("side_b"),
  aVotes: __t.u32().name("a_votes"),
  bVotes: __t.u32().name("b_votes"),
  eVotes: __t.u32().name("e_votes"),
  hot: __t.bool(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
});
