// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
});
export type Admin = __Infer<typeof Admin>;

export const Category = __t.object("Category", {
  slug: __t.string(),
  name: __t.string(),
  color: __t.string(),
  icon: __t.string(),
  blurb: __t.string(),
  sort: __t.u32(),
});
export type Category = __Infer<typeof Category>;

export const Chat = __t.object("Chat", {
  id: __t.u64(),
  topicId: __t.u64(),
  mode: __t.string(),
  a: __t.identity(),
  b: __t.identity(),
  status: __t.string(),
  scoreA: __t.i32(),
  scoreB: __t.i32(),
  likes: __t.u32(),
  msgCount: __t.u32(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
  lastAt: __t.timestamp(),
});
export type Chat = __Infer<typeof Chat>;

export const ChatLike = __t.object("ChatLike", {
  id: __t.u64(),
  chatId: __t.u64(),
  liker: __t.identity(),
});
export type ChatLike = __Infer<typeof ChatLike>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  chatId: __t.u64(),
  sender: __t.identity(),
  side: __t.string(),
  text: __t.string(),
  pts: __t.option(__t.i32()),
  why: __t.option(__t.string()),
  sentAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  recipient: __t.identity(),
  chatId: __t.u64(),
  topicId: __t.u64(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  username: __t.string(),
  online: __t.bool(),
  likes: __t.u32(),
  debates: __t.u32(),
  streak: __t.u32(),
  lastActiveDay: __t.u32(),
  membership: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const Ticket = __t.object("Ticket", {
  id: __t.u64(),
  identity: __t.identity(),
  topicId: __t.u64(),
  choice: __t.string(),
  mode: __t.string(),
  createdAt: __t.timestamp(),
});
export type Ticket = __Infer<typeof Ticket>;

export const Topic = __t.object("Topic", {
  id: __t.u64(),
  title: __t.string(),
  category: __t.string(),
  sideA: __t.string(),
  sideB: __t.string(),
  aVotes: __t.u32(),
  bVotes: __t.u32(),
  eVotes: __t.u32(),
  hot: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Topic = __Infer<typeof Topic>;

export const Username = __t.object("Username", {
  name: __t.string(),
  owner: __t.identity(),
});
export type Username = __Infer<typeof Username>;

export const Vote = __t.object("Vote", {
  id: __t.u64(),
  topicId: __t.u64(),
  voter: __t.identity(),
  choice: __t.string(),
});
export type Vote = __Infer<typeof Vote>;

