// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
});
export type Admin = __Infer<typeof Admin>;

export const Affinity = __t.object("Affinity", {
  id: __t.u64(),
  owner: __t.identity(),
  feature: __t.string(),
  score: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type Affinity = __Infer<typeof Affinity>;

export const AwardInput = __t.object("AwardInput", {
  messageId: __t.u64(),
  points: __t.u32(),
  reason: __t.string(),
});
export type AwardInput = __Infer<typeof AwardInput>;

export const CasualClock = __t.object("CasualClock", {
  chatId: __t.u64(),
  firstMessageAt: __t.timestamp(),
});
export type CasualClock = __Infer<typeof CasualClock>;

export const CasualSweepJob = __t.object("CasualSweepJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CasualSweepJob = __Infer<typeof CasualSweepJob>;

export const Category = __t.object("Category", {
  slug: __t.string(),
  name: __t.string(),
  color: __t.string(),
  icon: __t.string(),
  blurb: __t.string(),
  sort: __t.u32(),
});
export type Category = __Infer<typeof Category>;

export const Chat = __t.object("Chat", {
  id: __t.u64(),
  topicId: __t.u64(),
  mode: __t.string(),
  a: __t.identity(),
  b: __t.identity(),
  status: __t.string(),
  scoreA: __t.i32(),
  scoreB: __t.i32(),
  likes: __t.u32(),
  msgCount: __t.u32(),
  summary: __t.string(),
  phase: __t.string(),
  phaseStartedAt: __t.timestamp(),
  engagementStarter: __t.string(),
  currentTurn: __t.string(),
  remainingA: __t.u64(),
  remainingB: __t.u64(),
  openingA: __t.bool(),
  openingB: __t.bool(),
  closingA: __t.bool(),
  closingB: __t.bool(),
  yieldedSide: __t.string(),
  passesA: __t.u32(),
  passesB: __t.u32(),
  resultJson: __t.string(),
  createdAt: __t.timestamp(),
  lastAt: __t.timestamp(),
});
export type Chat = __Infer<typeof Chat>;

export const ChatLike = __t.object("ChatLike", {
  id: __t.u64(),
  chatId: __t.u64(),
  liker: __t.identity(),
});
export type ChatLike = __Infer<typeof ChatLike>;

export const ChatStats = __t.object("ChatStats", {
  chatId: __t.u64(),
  readers: __t.u32(),
});
export type ChatStats = __Infer<typeof ChatStats>;

export const ConvoMemory = __t.object("ConvoMemory", {
  id: __t.u64(),
  owner: __t.identity(),
  chatId: __t.u64(),
  shown: __t.u32(),
  lastShownAt: __t.timestamp(),
  opened: __t.bool(),
  read: __t.bool(),
});
export type ConvoMemory = __Infer<typeof ConvoMemory>;

export const Entity = __t.object("Entity", {
  id: __t.u64(),
  key: __t.string(),
  name: __t.string(),
});
export type Entity = __Infer<typeof Entity>;

export const EntityInput = __t.object("EntityInput", {
  name: __t.string(),
  weight: __t.f32(),
});
export type EntityInput = __Infer<typeof EntityInput>;

export const Interaction = __t.object("Interaction", {
  id: __t.u64(),
  owner: __t.identity(),
  topicId: __t.u64(),
  kind: __t.string(),
  at: __t.timestamp(),
});
export type Interaction = __Infer<typeof Interaction>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  chatId: __t.u64(),
  sender: __t.identity(),
  side: __t.string(),
  text: __t.string(),
  pts: __t.option(__t.i32()),
  why: __t.option(__t.string()),
  phase: __t.string(),
  sentAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  recipient: __t.identity(),
  chatId: __t.u64(),
  topicId: __t.u64(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  username: __t.string(),
  online: __t.bool(),
  likes: __t.u32(),
  debates: __t.u32(),
  streak: __t.u32(),
  lastActiveDay: __t.u32(),
  membership: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const PointAward = __t.object("PointAward", {
  id: __t.u64(),
  chatId: __t.u64(),
  side: __t.string(),
  messageId: __t.u64(),
  points: __t.u32(),
  reason: __t.string(),
  createdAt: __t.timestamp(),
});
export type PointAward = __Infer<typeof PointAward>;

export const PruneJob = __t.object("PruneJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PruneJob = __Infer<typeof PruneJob>;

export const ScoreState = __t.object("ScoreState", {
  chatId: __t.u64(),
  scoredCount: __t.u32(),
  finalized: __t.bool(),
});
export type ScoreState = __Infer<typeof ScoreState>;

export const Service = __t.object("Service", {
  identity: __t.identity(),
  label: __t.string(),
});
export type Service = __Infer<typeof Service>;

export const Submission = __t.object("Submission", {
  id: __t.u64(),
  chatId: __t.u64(),
  side: __t.string(),
  phase: __t.string(),
  text: __t.string(),
});
export type Submission = __Infer<typeof Submission>;

export const Tag = __t.object("Tag", {
  slug: __t.string(),
  name: __t.string(),
  sort: __t.u32(),
});
export type Tag = __Infer<typeof Tag>;

export const Ticket = __t.object("Ticket", {
  id: __t.u64(),
  identity: __t.identity(),
  topicId: __t.u64(),
  choice: __t.string(),
  mode: __t.string(),
  createdAt: __t.timestamp(),
});
export type Ticket = __Infer<typeof Ticket>;

export const Topic = __t.object("Topic", {
  id: __t.u64(),
  title: __t.string(),
  category: __t.string(),
  sideA: __t.string(),
  sideB: __t.string(),
  aVotes: __t.u32(),
  bVotes: __t.u32(),
  eVotes: __t.u32(),
  hot: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Topic = __Infer<typeof Topic>;

export const TopicEntity = __t.object("TopicEntity", {
  id: __t.u64(),
  topicId: __t.u64(),
  entityId: __t.u64(),
  weight: __t.f32(),
});
export type TopicEntity = __Infer<typeof TopicEntity>;

export const TopicMemory = __t.object("TopicMemory", {
  id: __t.u64(),
  owner: __t.identity(),
  topicId: __t.u64(),
  shown: __t.u32(),
  lastShownAt: __t.timestamp(),
  lastOpenAt: __t.timestamp(),
  engaged: __t.bool(),
  hiddenUntil: __t.timestamp(),
});
export type TopicMemory = __Infer<typeof TopicMemory>;

export const TopicMeta = __t.object("TopicMeta", {
  topicId: __t.u64(),
  tone: __t.string(),
  source: __t.string(),
  taggedAt: __t.timestamp(),
});
export type TopicMeta = __Infer<typeof TopicMeta>;

export const TopicTag = __t.object("TopicTag", {
  id: __t.u64(),
  topicId: __t.u64(),
  tag: __t.string(),
});
export type TopicTag = __Infer<typeof TopicTag>;

export const Username = __t.object("Username", {
  name: __t.string(),
  owner: __t.identity(),
});
export type Username = __Infer<typeof Username>;

export const Vote = __t.object("Vote", {
  id: __t.u64(),
  topicId: __t.u64(),
  voter: __t.identity(),
  choice: __t.string(),
});
export type Vote = __Infer<typeof Vote>;

